# Definindo nome da Pipeline
name: Devops CI-CD

on: 
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Autenticação do DockerHub
      uses: docker/login-action@v3.3.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PWD }}
    
    - name: Construção da Imagem Docker
      uses: docker/build-push-action@v6.7.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          rodrigoafonso/devops-kube-news:v${{ github.run_number }}
          rodrigoafonso/devops-kube-news:latest
  
jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Definindo o context  
      uses: Azure/k8s-set-context@v3.0
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }}
        
    
